package model;
// Generated 08/11/2016 17:45:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private Integer idDepartamento;
     private String setor;
     private String codigo;
     private Set funcionariodepartamentos = new HashSet(0);

    public Departamento() {
    }

    public Departamento(String setor, String codigo, Set funcionariodepartamentos) {
       this.setor = setor;
       this.codigo = codigo;
       this.funcionariodepartamentos = funcionariodepartamentos;
    }
   
    public Integer getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(Integer idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public String getSetor() {
        return this.setor;
    }
    
    public void setSetor(String setor) {
        this.setor = setor;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Set getFuncionariodepartamentos() {
        return this.funcionariodepartamentos;
    }
    
    public void setFuncionariodepartamentos(Set funcionariodepartamentos) {
        this.funcionariodepartamentos = funcionariodepartamentos;
    }




}


