package model;
// Generated 08/11/2016 17:45:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private Integer idFuncionario;
     private String nome;
     private String sexo;
     private String cpf;
     private String rg;
     private String email;
     private String dataNascimento;
     private String telefone;
     private String data;
     private String estadoCivil;
     private String uf;
     private String cep;
     private String endereco;
     private String cidade;
     private String numero;
     private String complemento;
     private String bairro;
     private Set funcionariodepartamentos = new HashSet(0);

    public Funcionario() {
    }

    public Funcionario(String nome, String sexo, String cpf, String rg, String email, String dataNascimento, String telefone, String data, String estadoCivil, String uf, String cep, String endereco, String cidade, String numero, String complemento, String bairro, Set funcionariodepartamentos) {
       this.nome = nome;
       this.sexo = sexo;
       this.cpf = cpf;
       this.rg = rg;
       this.email = email;
       this.dataNascimento = dataNascimento;
       this.telefone = telefone;
       this.data = data;
       this.estadoCivil = estadoCivil;
       this.uf = uf;
       this.cep = cep;
       this.endereco = endereco;
       this.cidade = cidade;
       this.numero = numero;
       this.complemento = complemento;
       this.bairro = bairro;
       this.funcionariodepartamentos = funcionariodepartamentos;
    }
   
    public Integer getIdFuncionario() {
        return this.idFuncionario;
    }
    
    public void setIdFuncionario(Integer idFuncionario) {
        this.idFuncionario = idFuncionario;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(String dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getData() {
        return this.data;
    }
    
    public void setData(String data) {
        this.data = data;
    }
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public Set getFuncionariodepartamentos() {
        return this.funcionariodepartamentos;
    }
    
    public void setFuncionariodepartamentos(Set funcionariodepartamentos) {
        this.funcionariodepartamentos = funcionariodepartamentos;
    }




}


