/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import dao.Dao;
import java.util.HashMap;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Departamento;
import model.Funcionario;
import model.Funcionariodepartamento;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author INFOMORAIS.COM
 */
public class Cons_Func extends javax.swing.JDialog {

    /**
     * Creates new form Cons_Func
     */
    public Cons_Func(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
         DefaultTableModel x=(DefaultTableModel) FuncionariosTable.getModel();
        FuncionariosTable.setRowSorter(new TableRowSorter(x));
        
        //DepartamentoCombo.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Controlador_op = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        FuncionariosTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        codigoField = new javax.swing.JTextField();
        tfField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ListaCompletaRadioButton = new javax.swing.JRadioButton();
        DepartamentoRadioButton = new javax.swing.JRadioButton();
        PesquisarButton = new javax.swing.JButton();
        VoltarButton = new javax.swing.JButton();
        DepartamentoCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        RelatorioButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Funcionários");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Registro de Funcionários Cadastrados");

        FuncionariosTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FuncionariosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        FuncionariosTable.setToolTipText("Clique em alguma das colunas para ordenar as informações");
        jScrollPane2.setViewportView(FuncionariosTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações:\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Identificador:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Código:");

        idField.setEditable(false);
        idField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        codigoField.setEditable(false);
        codigoField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel6.setText("Total Funcionários:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codigoField, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(codigoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\INFOMORAIS.COM\\Desktop\\Javaproject_atualizado\\Logos\\consultar_modificado.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pesquisa de Funcionários Por Atributos:");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Método de Pesquisa:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        Controlador_op.add(ListaCompletaRadioButton);
        ListaCompletaRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ListaCompletaRadioButton.setText("Lista Completa");
        ListaCompletaRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ListaCompletaRadioButtonStateChanged(evt);
            }
        });

        Controlador_op.add(DepartamentoRadioButton);
        DepartamentoRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DepartamentoRadioButton.setText("Por Departamento");
        DepartamentoRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                DepartamentoRadioButtonStateChanged(evt);
            }
        });

        PesquisarButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PesquisarButton.setText("Pesquisar");
        PesquisarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarButtonActionPerformed(evt);
            }
        });

        VoltarButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VoltarButton.setText("Voltar");
        VoltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarButtonActionPerformed(evt);
            }
        });

        DepartamentoCombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DepartamentoCombo.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Departamento:");

        RelatorioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RelatorioButton.setText("Relatório");
        RelatorioButton.setToolTipText("Gera  um Relatório de todos os funcionários cadastrados");
        RelatorioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatorioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ListaCompletaRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DepartamentoRadioButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DepartamentoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addGap(276, 276, 276))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PesquisarButton)
                .addGap(197, 197, 197)
                .addComponent(RelatorioButton)
                .addGap(18, 18, 18)
                .addComponent(VoltarButton))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DepartamentoRadioButton)
                    .addComponent(ListaCompletaRadioButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DepartamentoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PesquisarButton)
                    .addComponent(VoltarButton)
                    .addComponent(RelatorioButton)))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jDesktopPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarButtonActionPerformed
        //new Menu().setEnabled(true);

        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_VoltarButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
/*
// Pegar todos os pacientes do banco de dados
        List funcionarios = Dao.executarConsultaHQL("from Funcionario"); // usar o nome da classe e não da tabela        
        // Pegar o modelo da Tabela
        
        
        // Definir os nomes das colunas
        Vector colunas = new Vector();
        colunas.add("Nome");
        colunas.add("CPF");
        colunas.add("Sexo");
        colunas.add("Unidade Federativa");
        colunas.add("Data");
        
         // Definir os dados a partir da lista de pacientes
        Vector dados = new Vector();
        for (Object obj : funcionarios) {
            Funcionario f = (Funcionario)obj;
            
            Vector linha = new Vector();
            linha.add(f.getNome());
            linha.add(f.getCpf());
            linha.add(f.getSexo());
            linha.add(f.getUf().toString());
            linha.add(f.getData());
            
            dados.add(linha);
        }
        DefaultTableModel modelo = (DefaultTableModel)FuncionariosTable.getModel();
        modelo.setDataVector(dados, colunas); 
        
    */
    }//GEN-LAST:event_formWindowOpened

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
       //if (jRadioButton2.isSelected()){
           //DepartamentoCombo.setEnabled(false); 
       
        List departamentos = Dao.executarConsultaHQL("from Departamento");
        
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        modelo.addElement("");
        for (Object obj : departamentos) {
            Departamento d = (Departamento)obj;
            modelo.addElement(d.getSetor());
            
        }
        DepartamentoCombo.setModel(modelo);
        
        Vector colunas = new Vector();
        colunas.add("Nome");
        colunas.add("CPF");
        colunas.add("Sexo");
        colunas.add("Unidade Federativa");
        colunas.add("Data");
        
        DefaultTableModel funcionariosModelo = (DefaultTableModel)FuncionariosTable.getModel();
        funcionariosModelo.setColumnIdentifiers(colunas);
    }//GEN-LAST:event_formComponentShown

    private void PesquisarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarButtonActionPerformed
              if (ListaCompletaRadioButton.isSelected()){
           DepartamentoCombo.setEnabled(false);
           codigoField.setText(null);
            idField.setText(null);
        List funcionarios = Dao.executarConsultaHQL("from Funcionario"); 
    
        Vector colunas = new Vector();
        colunas.add("Nome");
        colunas.add("CPF");
        colunas.add("Sexo");
        colunas.add("Unidade Federativa");
        colunas.add("Data");
        
         
        Vector dados = new Vector();
        for (Object obj : funcionarios) {
            Funcionario f = (Funcionario)obj;
            
            Vector linha = new Vector();
            linha.add(f.getNome());
            linha.add(f.getCpf());
            linha.add(f.getSexo());
            linha.add(f.getUf().toString());
            linha.add(f.getData());
            
            dados.add(linha);
        }
        DefaultTableModel modelo = (DefaultTableModel)FuncionariosTable.getModel();
        modelo.setDataVector(dados, colunas); 
    }                                               
        else { 
            if(DepartamentoRadioButton.isSelected()){
            //DepartamentoCombo.setEnabled(true); 
            DefaultTableModel funcionariosModelo = (DefaultTableModel) FuncionariosTable.getModel();
            funcionariosModelo.setNumRows(0);
            
            int departamentoIndex = DepartamentoCombo.getSelectedIndex();
        if (departamentoIndex == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Você precisa selecionar um Departamento");
            
            codigoField.setText(null);
            idField.setText(null);
            DefaultTableModel funcionariosModelo1 = (DefaultTableModel) FuncionariosTable.getModel();
            funcionariosModelo1.setNumRows(0);
        }
               // List funcionarios = Dao.executarConsultaHQL("from Funcionario");
        //Funcionario f = (Funcionario) funcionarios.get(departamentoIndex -1);
            //NomeField.setText(f.getNome());
                  
                List departamentos = Dao.executarConsultaHQL("from Departamento");
        Departamento d = (Departamento) departamentos.get(departamentoIndex - 1);

        // Preencho o campo nome que não pode ser editado
        codigoField.setText(d.getCodigo());
        idField.setText(d.getIdDepartamento().toString());
        
        //possivel codigo para exibir o total de registros da tabela funcionarios no mysql
        //APRESENTANDO ERRO!
        //List funcionarios1 = Dao.executarConsultaHQL("SELECT COUNT (idFuncionario) FROM Funcionario");
        //Funcionario x = (Funcionario) funcionarios1.get(departamentoIndex - 1);
        //tfField.setText(x.toString());
        
         Vector colunas = new Vector();
        colunas.add("Nome");
        colunas.add("CPF");
        colunas.add("Sexo");
        colunas.add("Unidade Federativa");
        colunas.add("Data");
             
        
        Vector dados = new Vector();
        for (Object obj : d.getFuncionariodepartamentos()) {
            Funcionariodepartamento fd = (Funcionariodepartamento) obj;

            Vector linha = new Vector();
            linha.add(fd.getFuncionario().getNome());
            linha.add(fd.getFuncionario().getCpf());
            linha.add(fd.getFuncionario().getSexo());
            linha.add(fd.getFuncionario().getUf());
            linha.add(fd.getFuncionario().getData());

            dados.add(linha);
                          }
        DefaultTableModel funcionariosModelo2 = (DefaultTableModel) FuncionariosTable.getModel();
        funcionariosModelo2.setDataVector(dados, colunas);  
                      }
                   
                }
              /* rotina para tentar exibir uma mensagem de alerta caso nao haja radiobuttons selecionados.
              //Observação:apresentou falhas!
              else{
         if(DepartamentoRadioButton.setSelected(false)&&(ListaCompletaRadioButton.setSelected(false))){             
        javax.swing.JOptionPane.showMessageDialog(null,"Por favor selecione uma Opção!");
    }//GEN-LAST:event_PesquisarButtonActionPerformed
   } */
             
  }            
    private void DepartamentoRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_DepartamentoRadioButtonStateChanged
                if(DepartamentoRadioButton.isSelected()){
        DepartamentoCombo.setEnabled(true);
            /*DefaultTableModel funcionariosModelo = (DefaultTableModel) FuncionariosTable.getModel();
            funcionariosModelo.setNumRows(0);*/
        }
        else{
                if(ListaCompletaRadioButton.isSelected());{
            DepartamentoCombo.setEnabled(false);
            DepartamentoCombo.setSelectedItem(null);
           }                                                    
        }     
    }//GEN-LAST:event_DepartamentoRadioButtonStateChanged

    private void ListaCompletaRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ListaCompletaRadioButtonStateChanged
        //DefaultTableModel funcionariosModelo = (DefaultTableModel) FuncionariosTable.getModel();
            //funcionariosModelo.setNumRows(0);
    }//GEN-LAST:event_ListaCompletaRadioButtonStateChanged

    private void RelatorioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatorioButtonActionPerformed
        try {

            JasperReport report = JasperCompileManager.compileReport("src/view/FuncionarioREL.jrxml");

            JasperPrint reportPrint = JasperFillManager.fillReport(report, new HashMap(), Dao.getConnection());

            //JasperViewer.viewReport(reportPrint, false);
            JasperViewer jv=new JasperViewer(reportPrint,false);
            
             //linha para o relatório vir a frente das janelas
             jv.setVisible(true);//chama o relatporio para visualização
             jv.toFront();//
        }
        catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(null, ex);
    }//GEN-LAST:event_RelatorioButtonActionPerformed
  }   
 
             /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cons_Func.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cons_Func.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cons_Func.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cons_Func.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cons_Func dialog = new Cons_Func(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Controlador_op;
    private javax.swing.JComboBox<String> DepartamentoCombo;
    private javax.swing.JRadioButton DepartamentoRadioButton;
    private javax.swing.JTable FuncionariosTable;
    private javax.swing.JRadioButton ListaCompletaRadioButton;
    private javax.swing.JButton PesquisarButton;
    private javax.swing.JButton RelatorioButton;
    private javax.swing.JButton VoltarButton;
    private javax.swing.JTextField codigoField;
    private javax.swing.JTextField idField;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tfField;
    // End of variables declaration//GEN-END:variables
}
