/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import dao.Dao;
//import static groovy.xml.Entity.nbsp; importação para por caracteres de espaço em HTML no netbeans
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import javax.swing.Timer;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.export.JRHtmlExporter;
import net.sf.jasperreports.engine.export.JRPdfExporter;
import net.sf.jasperreports.view.JasperViewer;
import static org.slf4j.helpers.Util.report;
import javax.swing.JOptionPane;

/**
 *
 * @author INFOMORAIS.COM
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
        creditos= new Creditos();
        jDesktopPane1.add(creditos);
        
    }
    
 

    private Tela veiodaTelaPrincipal;
    
    public void enviaPalavra(Tela veiodaTelaPrincipal,String Nome){
        jLabel6.setText("Bem Vindo:"+" "+""+""+""+Nome);
        this.veiodaTelaPrincipal=veiodaTelaPrincipal;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel6 = new javax.swing.JLabel();
        CadastrarFuncButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        RecebeDataLabel = new javax.swing.JLabel();
        RecebeHoraLabel = new javax.swing.JLabel();
        ConsultarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        ArquivosMenu = new javax.swing.JMenu();
        FuncionariosMenu = new javax.swing.JMenu();
        CadastrarFuncMenuItem = new javax.swing.JMenuItem();
        ConsultarFuncMenuItem = new javax.swing.JMenuItem();
        ExcluirFuncMenuItem = new javax.swing.JMenuItem();
        DepartamentosMenu = new javax.swing.JMenu();
        Cad_DEptMenuItem = new javax.swing.JMenuItem();
        DptToFuncMenuItem = new javax.swing.JMenuItem();
        Show_DeptMenuItem = new javax.swing.JMenuItem();
        RelatóriosMenu = new javax.swing.JMenu();
        RelFuncionariosMenuItem = new javax.swing.JMenuItem();
        RelDepartamentosMenuItem = new javax.swing.JMenuItem();
        ExportaMenuItem = new javax.swing.JMenuItem();
        WEBmenuItem = new javax.swing.JMenuItem();
        Sobre_Menu = new javax.swing.JMenu();
        CreditosMenuItem = new javax.swing.JMenuItem();
        OpçõesMenu = new javax.swing.JMenu();
        TemasMenuItem = new javax.swing.JMenuItem();
        LogoutMenuItem = new javax.swing.JMenuItem();
        SairMenuItem = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem5.setText("jMenuItem5");

        jMenu6.setText("jMenu6");

        jMenuItem9.setText("jMenuItem9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("jLabel6");

        CadastrarFuncButton.setBackground(new java.awt.Color(204, 204, 204));
        CadastrarFuncButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\INFOMORAIS.COM\\Desktop\\Software\\Actions-contact-new-icon.png")); // NOI18N
        CadastrarFuncButton.setToolTipText("Cadastro de Funcionários\n");
        CadastrarFuncButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarFuncButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cadastrar Funcionários");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        RecebeDataLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        RecebeDataLabel.setForeground(new java.awt.Color(255, 255, 255));
        RecebeDataLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RecebeDataLabel.setText("jLabel7");

        RecebeHoraLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        RecebeHoraLabel.setForeground(new java.awt.Color(255, 255, 255));
        RecebeHoraLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RecebeHoraLabel.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(RecebeDataLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(RecebeHoraLabel)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RecebeDataLabel)
                    .addComponent(RecebeHoraLabel)))
        );

        ConsultarButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\INFOMORAIS.COM\\Desktop\\Software\\consultar_modificado.png")); // NOI18N
        ConsultarButton.setToolTipText("Consultar Funcionários");
        ConsultarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consultar Funcionários");

        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(CadastrarFuncButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(ConsultarButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap(238, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CadastrarFuncButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel2)))
                                .addGap(93, 93, 93)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel1))
                                    .addComponent(ConsultarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addGap(56, 56, 56)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ConsultarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CadastrarFuncButton, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ArquivosMenu.setText("Arquivo");
        ArquivosMenu.setName(""); // NOI18N
        jMenuBar1.add(ArquivosMenu);

        FuncionariosMenu.setText("Funcionários");

        CadastrarFuncMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        CadastrarFuncMenuItem.setIcon(new javax.swing.ImageIcon("C:\\Users\\INFOMORAIS.COM\\Desktop\\Software\\novo+.png")); // NOI18N
        CadastrarFuncMenuItem.setText("Cadastrar");
        CadastrarFuncMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarFuncMenuItemActionPerformed(evt);
            }
        });
        FuncionariosMenu.add(CadastrarFuncMenuItem);

        ConsultarFuncMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        ConsultarFuncMenuItem.setIcon(new javax.swing.ImageIcon("C:\\Users\\INFOMORAIS.COM\\Desktop\\Javaproject_atualizado\\Logos\\consultar_ver.png")); // NOI18N
        ConsultarFuncMenuItem.setText("Consultar");
        ConsultarFuncMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarFuncMenuItemActionPerformed(evt);
            }
        });
        FuncionariosMenu.add(ConsultarFuncMenuItem);

        ExcluirFuncMenuItem.setIcon(new javax.swing.ImageIcon("C:\\Users\\INFOMORAIS.COM\\Desktop\\Software\\Actions-application-exit-icon.png")); // NOI18N
        ExcluirFuncMenuItem.setText("Excluir");
        ExcluirFuncMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirFuncMenuItemActionPerformed(evt);
            }
        });
        FuncionariosMenu.add(ExcluirFuncMenuItem);

        jMenuBar1.add(FuncionariosMenu);

        DepartamentosMenu.setText("Departamentos");

        Cad_DEptMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        Cad_DEptMenuItem.setIcon(new javax.swing.ImageIcon("C:\\Users\\INFOMORAIS.COM\\Desktop\\Software\\novo+.png")); // NOI18N
        Cad_DEptMenuItem.setText("Cadastrar");
        Cad_DEptMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cad_DEptMenuItemActionPerformed(evt);
            }
        });
        DepartamentosMenu.add(Cad_DEptMenuItem);

        DptToFuncMenuItem.setIcon(new javax.swing.ImageIcon("C:\\Users\\INFOMORAIS.COM\\Desktop\\Software\\novo+.png")); // NOI18N
        DptToFuncMenuItem.setText("Departamento para Funcionario");
        DptToFuncMenuItem.setToolTipText("Este menu tem como finalidade o cadastro de um departamento para um Funcionário");
        DptToFuncMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DptToFuncMenuItemActionPerformed(evt);
            }
        });
        DepartamentosMenu.add(DptToFuncMenuItem);

        Show_DeptMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK));
        Show_DeptMenuItem.setIcon(new javax.swing.ImageIcon("C:\\Users\\INFOMORAIS.COM\\Desktop\\Software\\consultar_ver.png")); // NOI18N
        Show_DeptMenuItem.setText("Consultar");
        Show_DeptMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show_DeptMenuItemActionPerformed(evt);
            }
        });
        DepartamentosMenu.add(Show_DeptMenuItem);

        jMenuBar1.add(DepartamentosMenu);

        RelatóriosMenu.setText("Relatórios");

        RelFuncionariosMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        RelFuncionariosMenuItem.setIcon(new javax.swing.ImageIcon("C:\\Users\\INFOMORAIS.COM\\Desktop\\Software\\Relatorio2icon.png")); // NOI18N
        RelFuncionariosMenuItem.setText("Funcionários");
        RelFuncionariosMenuItem.setToolTipText("Visualizar o relatório de Funcionários");
        RelFuncionariosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelFuncionariosMenuItemActionPerformed(evt);
            }
        });
        RelatóriosMenu.add(RelFuncionariosMenuItem);

        RelDepartamentosMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        RelDepartamentosMenuItem.setText("Departamentos");
        RelDepartamentosMenuItem.setToolTipText("Visualizar o relatório de Departamentos");
        RelDepartamentosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelDepartamentosMenuItemActionPerformed(evt);
            }
        });
        RelatóriosMenu.add(RelDepartamentosMenuItem);

        ExportaMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        ExportaMenuItem.setIcon(new javax.swing.ImageIcon("C:\\Users\\INFOMORAIS.COM\\Desktop\\Software\\relatoriaPDF.png")); // NOI18N
        ExportaMenuItem.setText("Exportar  para PDF");
        ExportaMenuItem.setToolTipText("Exportará os Relatórios Existentes para arquivos PDF's Sobreescrevendo os já Salvos");
        ExportaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportaMenuItemActionPerformed(evt);
            }
        });
        RelatóriosMenu.add(ExportaMenuItem);

        WEBmenuItem.setIcon(new javax.swing.ImageIcon("C:\\Users\\INFOMORAIS.COM\\Desktop\\Software\\HTML_ICONE.jpg")); // NOI18N
        WEBmenuItem.setText("Exportar Para Web");
        WEBmenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WEBmenuItemActionPerformed(evt);
            }
        });
        RelatóriosMenu.add(WEBmenuItem);

        jMenuBar1.add(RelatóriosMenu);

        Sobre_Menu.setText("Sobre");

        CreditosMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK));
        CreditosMenuItem.setText("Créditos");
        CreditosMenuItem.setToolTipText("A autoria desta \"portentosa\" Aplicação.");
        CreditosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditosMenuItemActionPerformed(evt);
            }
        });
        Sobre_Menu.add(CreditosMenuItem);

        jMenuBar1.add(Sobre_Menu);

        OpçõesMenu.setText("Opções");

        TemasMenuItem.setText("Temas");
        TemasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemasMenuItemActionPerformed(evt);
            }
        });
        OpçõesMenu.add(TemasMenuItem);

        LogoutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        LogoutMenuItem.setIcon(new javax.swing.ImageIcon("C:\\Users\\INFOMORAIS.COM\\Desktop\\Software\\sair.png")); // NOI18N
        LogoutMenuItem.setText("Logout");
        LogoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutMenuItemActionPerformed(evt);
            }
        });
        OpçõesMenu.add(LogoutMenuItem);

        SairMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        SairMenuItem.setIcon(new javax.swing.ImageIcon("C:\\Users\\INFOMORAIS.COM\\Desktop\\Software\\download.jpg")); // NOI18N
        SairMenuItem.setText("Sair");
        SairMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairMenuItemActionPerformed(evt);
            }
        });
        OpçõesMenu.add(SairMenuItem);

        jMenuBar1.add(OpçõesMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        setSize(new java.awt.Dimension(500, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarFuncMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarFuncMenuItemActionPerformed
(new FuncCad(this,true)).setVisible(true);
//(new Cad_Func(this,true)).setVisible(true);
        /*CadFunc obj=new CadFunc();
jDesktopPane1.add(obj);
obj.setVisible(true);


        /*new CadClie().setVisible(true);
this.setEnabled(true);
        */
        //new Tela().show();
    }//GEN-LAST:event_CadastrarFuncMenuItemActionPerformed

    private void CadastrarFuncButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarFuncButtonActionPerformed
(new FuncCad(this,true)).setVisible(true);
     // new CadClie().setVisible(true);
    // this.dispose();       
    }//GEN-LAST:event_CadastrarFuncButtonActionPerformed

    private void SairMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairMenuItemActionPerformed

 //O CÓDIGO ABAIXO SERVE PARA QUESTIONAR O FECHAMENTO DE UMA APLICAÇÃO,se marcado sim na caixa de diálogo a aplicação será de fato fechada       
        int opcao=JOptionPane.showConfirmDialog(null,"Deseja realmente sair da Aplicação?","Atenção", JOptionPane.YES_OPTION);

if (opcao==JOptionPane.YES_OPTION){
        System.exit(0);        
    }//GEN-LAST:event_SairMenuItemActionPerformed
   }
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        
    }//GEN-LAST:event_formComponentShown

    private void LogoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutMenuItemActionPerformed
new Tela().setVisible(true);  
this.dispose();
    }//GEN-LAST:event_LogoutMenuItemActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      Date dataSistema= new Date();
      SimpleDateFormat formato= new SimpleDateFormat("dd/MM/yyyy");
      RecebeDataLabel.setText(formato.format(dataSistema));
      
      Timer timer=new Timer(1000,new hora());
      timer.start();
    }//GEN-LAST:event_formWindowOpened

    private void ConsultarFuncMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarFuncMenuItemActionPerformed
(new Cons_Func(this,true)).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarFuncMenuItemActionPerformed

    private void ConsultarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarButtonActionPerformed
(new Cons_Func(this,true)).setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarButtonActionPerformed

    private void DptToFuncMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DptToFuncMenuItemActionPerformed
(new CadastrarFuncionarioDepartamento(this,true)).setVisible(true);
    }//GEN-LAST:event_DptToFuncMenuItemActionPerformed

    private void RelFuncionariosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelFuncionariosMenuItemActionPerformed
           try {
       
           JasperReport report = JasperCompileManager.compileReport("src/view/FuncionarioREL.jrxml");
       
       JasperPrint reportPrint = JasperFillManager.fillReport(report, new HashMap(), Dao.getConnection());
       
       JasperViewer.viewReport(reportPrint, false);}
       catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(null, ex);
    }
    }//GEN-LAST:event_RelFuncionariosMenuItemActionPerformed

    private void RelDepartamentosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelDepartamentosMenuItemActionPerformed
                try {
       
           JasperReport report = JasperCompileManager.compileReport("src/view/DepartamentoREL.jrxml");
       
       JasperPrint reportPrint = JasperFillManager.fillReport(report, new HashMap(), Dao.getConnection());
       
       JasperViewer.viewReport(reportPrint, false);}
       catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(null, ex);
    }
    }//GEN-LAST:event_RelDepartamentosMenuItemActionPerformed

    private void ExcluirFuncMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirFuncMenuItemActionPerformed
      (new Excluir_Func(this,true)).setVisible(true);
    }//GEN-LAST:event_ExcluirFuncMenuItemActionPerformed

    private void ExportaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportaMenuItemActionPerformed
        try {
 
  JasperReport report = JasperCompileManager.compileReport("src/view/DepartamentoREL.jrxml");
  JasperReport report1 = JasperCompileManager.compileReport("src/view/FuncionarioREL.jrxml");
  //Preenchendo o relatório com os dados do Data Source
  JasperPrint reportPrint = JasperFillManager.fillReport(report, new HashMap(), 
                            Dao.getConnection());

  //Exportando
  JRPdfExporter pdfExporter = new JRPdfExporter();
  pdfExporter.setParameter(JRExporterParameter.JASPER_PRINT, reportPrint);
  pdfExporter.setParameter(JRExporterParameter.OUTPUT_FILE_NAME, 
                           "src/view/DepartamentoREL.pdf");
  pdfExporter.exportReport();
  
  //Exportando Relatório de Clientes
  
  
  //Preenchendo o relatório com os dados do Data Source
  JasperPrint reportPrint1 = JasperFillManager.fillReport(report1, new HashMap(), 
                            Dao.getConnection());
  //Exportando
  JRPdfExporter pdfExporter1 = new JRPdfExporter();
  pdfExporter1.setParameter(JRExporterParameter.JASPER_PRINT, reportPrint1);
  pdfExporter1.setParameter(JRExporterParameter.OUTPUT_FILE_NAME, 
                           "src/view/FuncionarioREL.pdf");
  pdfExporter1.exportReport();
  
  javax.swing.JOptionPane.showMessageDialog(this, "Relatórios Exportados em PDF com Sucesso");

} 
catch (Exception ex) {
  javax.swing.JOptionPane.showMessageDialog(null, ex);
}


    }//GEN-LAST:event_ExportaMenuItemActionPerformed

    private void Cad_DEptMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cad_DEptMenuItemActionPerformed
       (new CadDpt(this,true)).setVisible(true);
    }//GEN-LAST:event_Cad_DEptMenuItemActionPerformed

    private void Show_DeptMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show_DeptMenuItemActionPerformed
       (new ShowDpt(this,true)).setVisible(true);
    }//GEN-LAST:event_Show_DeptMenuItemActionPerformed

    private void WEBmenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WEBmenuItemActionPerformed
        try {
            
            //Exportando Relatório de Departamentos para HTML
  JasperReport report = JasperCompileManager.compileReport("src/view/DepartamentoREL.jrxml");
 
 
  //Preenchendo o relatório com os dados do Data Source//RETIRADO DO POWERPOINT DO JASPER REPORT
   JasperPrint reportPrint = JasperFillManager.fillReport(report, new HashMap(), 
                            Dao.getConnection());

  //Exportando
  JRHtmlExporter HTMLExporter = new JRHtmlExporter();
  HTMLExporter.setParameter(JRExporterParameter.JASPER_PRINT, reportPrint);
  HTMLExporter.setParameter(JRExporterParameter.OUTPUT_FILE_NAME, 
                           "src/view/Departamento.html");
  HTMLExporter.exportReport();

  //Exportando Relatório de Funcionários para HTML
  
   JasperReport report1 = JasperCompileManager.compileReport("src/view/FuncionarioREL.jrxml");
  
//Preenchendo o relatório com os dados da classe DAO através de seu método getConnection//ESTE COMENTÁRIO E O CORRETO
  JasperPrint reportPrint1 = JasperFillManager.fillReport(report1, new HashMap(), 
                            Dao.getConnection());
  //Exportando
  JRHtmlExporter HTMLExporter1 = new JRHtmlExporter();
  HTMLExporter1.setParameter(JRExporterParameter.JASPER_PRINT, reportPrint1);
  HTMLExporter1.setParameter(JRExporterParameter.OUTPUT_FILE_NAME, 
                           "src/view/Funcionarios.html");
 HTMLExporter1.exportReport();
  
  javax.swing.JOptionPane.showMessageDialog(this, "Relatórios Exportados para WEB com Sucesso");
  
} 
catch (Exception ex) {
  javax.swing.JOptionPane.showMessageDialog(null, ex);
}

    }//GEN-LAST:event_WEBmenuItemActionPerformed

    private void CreditosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditosMenuItemActionPerformed
        creditos.setVisible(true);
    }//GEN-LAST:event_CreditosMenuItemActionPerformed

    private void TemasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemasMenuItemActionPerformed
     (new Temas(this,true)).setVisible(true);
    }//GEN-LAST:event_TemasMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ArquivosMenu;
    private javax.swing.JMenuItem Cad_DEptMenuItem;
    private javax.swing.JButton CadastrarFuncButton;
    private javax.swing.JMenuItem CadastrarFuncMenuItem;
    private javax.swing.JButton ConsultarButton;
    private javax.swing.JMenuItem ConsultarFuncMenuItem;
    private javax.swing.JMenuItem CreditosMenuItem;
    private javax.swing.JMenu DepartamentosMenu;
    private javax.swing.JMenuItem DptToFuncMenuItem;
    private javax.swing.JMenuItem ExcluirFuncMenuItem;
    private javax.swing.JMenuItem ExportaMenuItem;
    private javax.swing.JMenu FuncionariosMenu;
    private javax.swing.JMenuItem LogoutMenuItem;
    private javax.swing.JMenu OpçõesMenu;
    private javax.swing.JLabel RecebeDataLabel;
    private javax.swing.JLabel RecebeHoraLabel;
    private javax.swing.JMenuItem RelDepartamentosMenuItem;
    private javax.swing.JMenuItem RelFuncionariosMenuItem;
    private javax.swing.JMenu RelatóriosMenu;
    private javax.swing.JMenuItem SairMenuItem;
    private javax.swing.JMenuItem Show_DeptMenuItem;
    private javax.swing.JMenu Sobre_Menu;
    private javax.swing.JMenuItem TemasMenuItem;
    private javax.swing.JMenuItem WEBmenuItem;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

 private Creditos creditos;   
    class hora implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e){
            Calendar now=Calendar.getInstance();
            RecebeHoraLabel.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        }
    }

}//fim da classe principal
